### ISSUE TITLE
Create globally unique identifier per microvm

### ISSUE THREAD

**Issue by richardcase** [weaveworks/flintlock#291]
**Describe the solution you'd like:**
Currently, the identifier for a microvm is a combination of namespace and name. We should also create an identifier that is globally/universally unique as well (i.e. a UUID/GUID).  This will stop the unlikely but possible (this has happened in CAPA) scenario where 2 separate management clusters create a cluster with the same name/namespace.

We should also be able to get the microvm details with this id. 

**Why do you want this feature:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by yitsushi** [comment]
It's not only if two separate management cluster wants to create with the same `ns/name`, it can be an issue on "update" too, because if the new one (recreate) lands on the same host machine as the old version while it's still running, it will fail to create and start the microvm from the new spec until the old one is terminated.
